### PR TITLE
COMPATIBILITY: Modernize the component

### PR DESCRIPTION
**Pull request by Arkshine**
This PR modernizes the components:
* Use the new header API
* Convert widget to glimmer components
* Move settings description to locale file
* Add acceptance tests
* Add CI workflow config file

Other changes made:
* `theme` setting is now defaulted to `auto.`  
* Add a loading spinner until the iframe is loaded.
* Color scheme detection relies on the Discourse CSS `--scheme-type` variable instead of the system.

https://github.com/user-attachments/assets/a24cacaf-7bf1-4874-84e2-592ecfb32126

### CODE REVIEW

**Comment by angusmcleod** [comment]
@Arkshine Amazing! Thank you.

**Comment by angusmcleod** [comment]
The workflow isn't being picked up. Is the path right?

**Comment by Arkshine** [comment]
> The workflow isn't being picked up. Is the path right?

~~You're right, the path was wrong, but it doesn't seem to have an effect. Is it required to be named "component-linting.yml"?~~
That doesn't seem to be the case. Not sure why now. Is it configured on this repository?

**Comment by angusmcleod** [comment]
@Arkshine Thanks again.

**Pull request merged**
